from_json:  ../data/inspired/test_p2.jsonl
max_tokens: 1024
use_related_knowledge: 0
n_threads: 1
n_samples: -1
pretrained_model_name_or_path: ../../LLM/Llama2-Chinese-7b-Chat
to_json: llama/c1/inspired_test.jsonl

